parameters:
#    ascuntar_sigpro_prestamos.example.class: Ascuntar\Sigpro\PrestamosBundle\Example

services:
#    ascuntar_sigpro_prestamos.example:
#        class: %ascuntar_sigpro_prestamos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
